from __future__ import annotations

import json
import re
from pathlib import Path
from textwrap import dedent

from .guards import assert_safe_repo_path
from .schemas import CrewManifest


def slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_") or "generated_crew"


class CrewFactory:
    def __init__(self, repo_root: Path):
        self.repo_root = repo_root

    def blueprint_from_goal(self, goal: str) -> CrewManifest:
        slug = slugify(goal.replace("crew", ""))[:48]
        purpose = goal.strip().rstrip(".")
        return CrewManifest(
            id=slug,
            name=" ".join(part.capitalize() for part in slug.split("_")),
            purpose=purpose,
            inputs_schema=f"crews/generated/{slug}/schemas/input.schema.json",
            outputs_schema=f"crews/generated/{slug}/schemas/output.schema.json",
            tools=["db.read", "db.write", "feedback.create"],
            permissions={
                "read_db": True,
                "write_db": True,
                "send_email": "approval_required",
                "charge_customer": False,
            },
            entrypoint=f"crews/generated/{slug}/crew.py",
            evals=[f"crews/generated/{slug}/evals/basic.yaml"],
        )

    def scaffold(self, manifest: CrewManifest) -> list[Path]:
        base = self.repo_root / "crews" / "generated" / manifest.id
        written: list[Path] = []
        files = {
            "manifest.json": json.dumps(manifest.model_dump(), indent=2) + "\n",
            "README.md": self._readme(manifest),
            "crew.py": self._crew_py(manifest),
            "agents.yaml": self._agents_yaml(manifest),
            "tasks.yaml": self._tasks_yaml(manifest),
            "tools.py": self._tools_py(manifest),
            "schemas/input.schema.json": self._input_schema(manifest),
            "schemas/output.schema.json": self._output_schema(manifest),
            "evals/basic.yaml": self._basic_eval(manifest),
            "tests/test_contract.py": self._contract_test(manifest),
        }
        for relative, content in files.items():
            path = assert_safe_repo_path(self.repo_root, base / relative)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            written.append(path)
        return written

    def _readme(self, manifest: CrewManifest) -> str:
        return dedent(f"""
        # {manifest.name}

        Purpose: {manifest.purpose}

        This crew was generated by Hermes. Review `manifest.json`, permissions, schemas,
        and evals before registering it in production.

        ## Run locally

        ```bash
        PYTHONPATH=packages:. python crews/generated/{manifest.id}/crew.py
        ```
        """).lstrip()

    def _crew_py(self, manifest: CrewManifest) -> str:
        return dedent(f"""
        from __future__ import annotations

        import os
        from typing import Any

        CREW_ID = "{manifest.id}"
        CREW_NAME = "{manifest.name}"


        def deterministic_response(payload: dict[str, Any]) -> dict[str, Any]:
            message = payload.get("message") or payload.get("input") or ""
            return {{
                "crew_id": CREW_ID,
                "status": "completed",
                "summary": f"{{CREW_NAME}} received: {{message}}",
                "needs_human": False,
                "next_actions": [
                    "Review generated crew manifest",
                    "Attach app-specific tools",
                    "Add eval cases before production use",
                ],
            }}


        def kickoff(payload: dict[str, Any]) -> dict[str, Any]:
            '''Run this crew.

            The deterministic fallback keeps local demos working without model keys.
            When `OPENAI_API_KEY` is present and CrewAI is installed, replace this body
            with Agent/Task/Crew orchestration or load from agents.yaml/tasks.yaml.
            '''
            if not os.getenv("OPENAI_API_KEY"):
                return deterministic_response(payload)

            try:
                from crewai import Agent, Crew, Process, Task
            except Exception:
                return deterministic_response(payload)

            agent = Agent(
                role="{manifest.name} Specialist",
                goal="{manifest.purpose}",
                backstory="You are a generated Hermes crew specialist with strict tool permissions.",
                verbose=True,
            )
            task = Task(
                description="Complete the requested job using this payload: {{payload}}",
                expected_output="A concise JSON-compatible result with summary, needs_human, and next_actions.",
                agent=agent,
            )
            crew = Crew(agents=[agent], tasks=[task], process=Process.sequential, verbose=True)
            result = crew.kickoff(inputs={{"payload": payload}})
            return {{"crew_id": CREW_ID, "status": "completed", "summary": str(result), "needs_human": False}}


        if __name__ == "__main__":
            print(kickoff({{"message": "Smoke test generated crew"}}))
        """).lstrip()

    def _agents_yaml(self, manifest: CrewManifest) -> str:
        return dedent(f"""
        specialist:
          role: "{manifest.name} Specialist"
          goal: "{manifest.purpose}"
          backstory: "A generated Hermes crew agent. Review permissions before production use."
          verbose: true
        """).lstrip()

    def _tasks_yaml(self, manifest: CrewManifest) -> str:
        return dedent(f"""
        main_task:
          description: "Execute the {manifest.name} workflow for the provided input payload."
          expected_output: "JSON with status, summary, needs_human, and next_actions."
          agent: specialist
        """).lstrip()

    def _tools_py(self, manifest: CrewManifest) -> str:
        return dedent(f"""
        '''Tool bindings for {manifest.name}.

        Keep tool permissions aligned with manifest.json.
        '''

        ALLOWED_TOOLS = {manifest.tools!r}
        PERMISSIONS = {manifest.permissions!r}


        def assert_tool_allowed(tool_name: str) -> None:
            if tool_name not in ALLOWED_TOOLS:
                raise PermissionError(f"Tool not allowed for this crew: {{tool_name}}")
        """).lstrip()

    def _input_schema(self, manifest: CrewManifest) -> str:
        return json.dumps({
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": f"{manifest.name} Input",
            "type": "object",
            "properties": {
                "message": {"type": "string"},
                "context": {"type": "object"},
            },
            "required": ["message"],
            "additionalProperties": True,
        }, indent=2) + "\n"

    def _output_schema(self, manifest: CrewManifest) -> str:
        return json.dumps({
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": f"{manifest.name} Output",
            "type": "object",
            "properties": {
                "crew_id": {"type": "string"},
                "status": {"type": "string"},
                "summary": {"type": "string"},
                "needs_human": {"type": "boolean"},
                "next_actions": {"type": "array", "items": {"type": "string"}},
            },
            "required": ["crew_id", "status", "summary", "needs_human"],
            "additionalProperties": True,
        }, indent=2) + "\n"

    def _basic_eval(self, manifest: CrewManifest) -> str:
        return dedent(f"""
        name: {manifest.id}_basic
        input:
          message: "Run the happy path for {manifest.name}."
        expected:
          must_include:
            - "status"
            - "summary"
          needs_human: false
        """).lstrip()

    def _contract_test(self, manifest: CrewManifest) -> str:
        return dedent(f"""
        import importlib.util
        from pathlib import Path


        def test_{manifest.id}_kickoff_contract():
            crew_file = Path(__file__).resolve().parents[1] / "crew.py"
            spec = importlib.util.spec_from_file_location("generated_{manifest.id}", crew_file)
            module = importlib.util.module_from_spec(spec)
            assert spec and spec.loader
            spec.loader.exec_module(module)
            result = module.kickoff({{"message": "contract smoke test"}})
            assert result["crew_id"] == "{manifest.id}"
            assert "summary" in result
            assert "needs_human" in result
        """).lstrip()
